version: '3.4'

services:

  magento_db:
    container_name: magento_db
    image: mariadb:10.4
    restart: "always"
    environment:
      - MARIADB_DATABASE=magento_db
      - MARIADB_USER=$MAGENTO_DB_USER
      - MARIADB_PASSWORD=$MAGENTO_DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MAGENTO_DB_ROOT_PASSWORD
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql

  magento_elastic_search:
    container_name: magento_elastic_search
    image: elasticsearch:8.4.2
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - discovery.type=single-node
    # stdin_open: true
    # tty: true       
    # command: bash
    command: bin/elasticsearch
    volumes:
      - ./docker-data/elasticsearch:/usr/share/elasticsearch/data

  magento_adminer:
    container_name: magento_adminer
    image: adminer


  magento_installer:
    build: 
      context: ./magento_installer
      args:
        - MAGENTO_PUBLIC_KEY=$MAGENTO_PUBLIC_KEY
        - MAGENTO_PRIVATE_KEY=$MAGENTO_PRIVATE_KEY
    restart: "no"
    # stdin_open: true
    # tty: true       
    # command: bash
    command: ./magento setup:install --db-host=magento_db --db-name=magento_db --db-user=$MAGENTO_DB_USER --db-password=$MAGENTO_DB_PASSWORD --admin-firstname=Magento --admin-lastname=User --admin-email=test@exampl.com  --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=magento_elastic_search --elasticsearch-port=9200
    depends_on:
      - magento_db
    # Note - run this in compatibility mode
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    environment:
      - COMPOSER_MEMORY_LIMIT=10M

