version: '3.4'

services:

  magento_db:
    container_name: magento_db
    image: mariadb:10.4
    restart: "always"
    environment:
      - MARIADB_DATABASE=magento_db
      - MARIADB_USER=$MAGENTO_DB_USER
      - MARIADB_PASSWORD=$MAGENTO_DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MAGENTO_DB_ROOT_PASSWORD
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql

  magento_elastic_search:
    container_name: magento_elastic_search
    image: elasticsearch:8.4.2
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    command: bin/elasticsearch
    # command: bin/elasticsearch-reset-password -u elastic
    volumes:
      - ./docker-data/elasticsearch:/usr/share/elasticsearch/data
      - ./docker-data/elasticsearch-tmp:/tmp

  magento_adminer:
    container_name: magento_adminer
    image: adminer
    ports:
      - 8080:8080

  magento:
    build: 
      context: ./magento
      args:
        - MAGENTO_PUBLIC_KEY=$MAGENTO_PUBLIC_KEY
        - MAGENTO_PRIVATE_KEY=$MAGENTO_PRIVATE_KEY
    restart: "no"
    # tty: true
    # stdin_open: true
    # command: sh
    # Phase 1 - Initialise 
    #command: composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.5 .
    # Phase 2 - Install
    # command: composer install
    # Phase 3 - Setup
    # command: ./bin/magento setup:install --db-host=magento_db --db-name=magento_db --db-user=$MAGENTO_DB_USER --db-password=$MAGENTO_DB_PASSWORD --admin-firstname=Magento --admin-lastname=User --admin-email=test@example.com  --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=magento_elastic_search --elasticsearch-port=9200 --elasticsearch-enable-auth=false
    volumes:
      - ./src:/var/www/html
    depends_on:
      - magento_db
      - magento_elastic_search
    environment:
      - MAGENTO_DB_USER=$MAGENTO_DB_USER
      - MAGENTO_DB_PASSWORD=$MAGENTO_DB_PASSWORD
    # Note - run this in compatibility mode
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    ports:
      - 8000:80

